# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent_events',
            name='created',
        ),
        migrations.RemoveField(
            model_name='recent_events',
            name='modified',
        ),
        migrations.AddField(
            model_name='recent_events',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
