# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-18 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161018_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
